import { Injectable } from '@nestjs/common';
import * as puppeteer from 'puppeteer-core';
import { BrandingService } from '@modules/admin/branding.service';
import { Decimal } from 'decimal.js';

export interface StatementLine {
  date: Date;
  description: string;
  debit: Decimal | null;
  credit: Decimal | null;
  balance: Decimal;
}

export interface StatementData {
  accountNumber: string;
  accountHolder: string;
  currency: string;
  from: Date;
  to: Date;
  openingBalance: Decimal;
  closingBalance: Decimal;
  lines: StatementLine[];
}

@Injectable()
export class StatementPdfService {
  constructor(private readonly brandingService: BrandingService) {}

  async generate(tenantId: string, data: StatementData): Promise<Buffer> {
    const logoDataUri = await this.brandingService.getLogoAsDataUri(tenantId);

    const logoHtml = logoDataUri
      ? `<img src="${logoDataUri}" alt="Bank Logo" style="max-height:60px;max-width:200px;" />`
      : '<span style="font-size:1.4rem;font-weight:bold;">Core Banking</span>';

    const rows = data.lines
      .map(
        (l) => `
      <tr>
        <td>${l.date.toLocaleDateString('en-NG')}</td>
        <td>${l.description}</td>
        <td style="text-align:right">${l.debit ? l.debit.toFixed(2) : ''}</td>
        <td style="text-align:right">${l.credit ? l.credit.toFixed(2) : ''}</td>
        <td style="text-align:right">${l.balance.toFixed(2)}</td>
      </tr>`,
      )
      .join('');

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: Arial, sans-serif; font-size: 12px; margin: 40px; color: #333; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; border-bottom: 2px solid #003366; padding-bottom: 12px; }
    .account-info { margin-bottom: 20px; }
    .account-info p { margin: 4px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background: #003366; color: white; padding: 8px; text-align: left; }
    td { padding: 6px 8px; border-bottom: 1px solid #ddd; }
    tr:nth-child(even) { background: #f5f7fa; }
    .footer { margin-top: 32px; font-size: 10px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 8px; }
    .summary { margin-top: 16px; text-align: right; font-weight: bold; }
  </style>
</head>
<body>
  <div class="header">
    ${logoHtml}
    <div style="text-align:right">
      <strong>Account Statement</strong><br/>
      ${data.from.toLocaleDateString('en-NG')} — ${data.to.toLocaleDateString('en-NG')}
    </div>
  </div>
  <div class="account-info">
    <p><strong>Account Holder:</strong> ${data.accountHolder}</p>
    <p><strong>Account Number:</strong> ${data.accountNumber}</p>
    <p><strong>Currency:</strong> ${data.currency}</p>
    <p><strong>Opening Balance:</strong> ${data.currency} ${data.openingBalance.toFixed(2)}</p>
  </div>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th style="text-align:right">Debit (${data.currency})</th>
        <th style="text-align:right">Credit (${data.currency})</th>
        <th style="text-align:right">Balance (${data.currency})</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <div class="summary">
    Closing Balance: ${data.currency} ${data.closingBalance.toFixed(2)}
  </div>
  <div class="footer">
    Generated by Core Banking System on ${new Date().toLocaleString('en-NG')}
  </div>
</body>
</html>`;

    const browser = await puppeteer.launch({
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH ?? '/usr/bin/chromium-browser',
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
      headless: true,
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      const pdfBuffer = await page.pdf({
        format: 'A4',
        margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
      });
      return Buffer.from(pdfBuffer);
    } finally {
      await browser.close();
    }
  }
}
