[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "app"

[services.networking]
[[services.networking.tcpProxies]]
applicationPort = 3000
